version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-registration-frontend
    ports:
      - "4200:80"
  nginx:
    image: nginx:latest
    container_name: or-frontend-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
